import { Address } from "viem";

export const CONTRACT_ADDRESSES = {
  MOOVE_NFT: (process.env.NEXT_PUBLIC_MOOVE_NFT_ADDRESS as Address) || "0x...",
  MOOVE_AUCTION:
    (process.env.NEXT_PUBLIC_MOOVE_AUCTION_ADDRESS as Address) || "0x...",
  MOOVE_ACCESS_CONTROL:
    (process.env.NEXT_PUBLIC_MOOVE_ACCESS_CONTROL_ADDRESS as Address) ||
    "0x...",
  MOOVE_RENTAL_PASS:
    (process.env.NEXT_PUBLIC_MOOVE_RENTAL_PASS_ADDRESS as Address) || "0x...",
} as const;

export const SUPPORTED_CHAINS = {
  SEPOLIA: 11155111,
  LOCALHOST: 1337,
} as const;

// ABI imports (these will be generated by deploy script)
import MooveNFTABI from "../../artifacts/contracts/MooveNFT.sol/MooveNFT.json";
import MooveAuctionABI from "../../artifacts/contracts/MooveAuction.sol/MooveAuction.json";
import MooveAccessControlABI from "../../artifacts/contracts/MooveAccessControl.sol/MooveAccessControl.json";
import MooveRentalPassABI from "../../artifacts/contracts/MooveRentalPass.sol/MooveRentalPass.json";

export const contracts = {
  MooveAccessControl: {
    address: CONTRACT_ADDRESSES.MOOVE_ACCESS_CONTROL,
    abi: MooveAccessControlABI,
  },
  MooveAuction: {
    address: CONTRACT_ADDRESSES.MOOVE_AUCTION,
    abi: MooveAuctionABI,
  },
  MooveNFT: {
    address: CONTRACT_ADDRESSES.MOOVE_NFT,
    abi: MooveNFTABI,
  },
  MooveRentalPass: {
    address: CONTRACT_ADDRESSES.MOOVE_RENTAL_PASS,
    abi: MooveRentalPassABI,
  },
} as const;
