import { Address } from "viem";

export const CONTRACT_ADDRESSES = {
  MOOVE_NFT: (process.env.NEXT_PUBLIC_MOOVE_NFT_ADDRESS as Address) || "0x...",
  MOOVE_AUCTION:
    (process.env.NEXT_PUBLIC_MOOVE_AUCTION_ADDRESS as Address) || "0x...",
} as const;

export const SUPPORTED_CHAINS = {
  SEPOLIA: 11155111,
  LOCALHOST: 1337,
} as const;

// ABI imports (these will be generated by deploy script)
import MooveNFTABI from "../../artifacts/contracts/MooveNFT.sol/MooveNFT.json";
import MooveAuctionABI from "../../artifacts/contracts/MooveAuction.sol/MooveAuction.json";

export const contracts = {
  MooveNFT: {
    address: CONTRACT_ADDRESSES.MOOVE_NFT,
    abi: MooveNFTABI,
  },
  MooveAuction: {
    address: CONTRACT_ADDRESSES.MOOVE_AUCTION,
    abi: MooveAuctionABI,
  },
} as const;
